// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://knp6iemx6jgvhfkmf2mpa6rcfy.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bksegct4dfgz5fofkzglka6gzu",
    "aws_content_delivery_bucket": "mychool-20200323170223-hostingbucket-test",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "http://mychool-20200323170223-hostingbucket-test.s3-website.ap-south-1.amazonaws.com"
};


export default awsmobile;
